[cursor]
vi_mode_style = "Beam"

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 12.5

[font.normal]
family = "Hack Nerd Font"

[scrolling]
history = 2000

[selection]
save_to_clipboard = true

[window]
opacity = 0.98
